version: "3.8"
services:

  php:
    build:
      context: ./..
      dockerfile: ./.docker/php/Dockerfile
    working_dir: /srv
    volumes:
      - ./../:/srv:delegated

  nginx:
    image: nginx:1.19.4-alpine
    volumes:
      - ./../www:/srv/www:delegated
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:delegated
    environment:
      - NGINX_PHP_HOST=php
    ports:
      - 90:80